# pgadmin-servers-cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-servers
  labels:
    app: pgadmin
data:
  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": "PostgreSQL",
          "Group": "Predefiniti",
          "Host": "postgres.svc.cluster.local",
          "Port": 5432,
          "MaintenanceDB": "postgres",
          "Username": "postgres",
          "SSLMode": "prefer"
        }
      }
    }