# secret-pgadmin.yaml
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  labels:
    environment: staging
type: Opaque
stringData:
  PGADMIN_DEFAULT_EMAIL: "admin@zmenu.next"   # cambia!
  PGADMIN_DEFAULT_PASSWORD: "CambiaQuestaPassword_MoltoForte"        # cambia!