apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: postgres-local
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - name: psql
      port: 5432
      targetPort: 5432
      