apiVersion: v1
kind: ServiceAccount
metadata:
  name: zmenu-frontend-serviceaccount
secrets:
  - name: devops-zmenu-basic-auth
  - name: quay-zmenu-credentials
imagePullSecrets:
  - name: quay-zmenu-credentials
  