# secret-ghcr-pull.yaml
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-creds
  labels:
    environment: staging
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiei1yb2JlcnRvLXBpdmEiLCJwYXNzd29yZCI6ImdocF9jTWlQUDNQZzRJWlYzSDBEZ2ozRWlwc2RRbDByT2wwUDVHSlYiLCJhdXRoIjoiZWkxeWIySmxjblJ2TFhCcGRtRTZaMmh3WDJOTmFWQlFNMUJuTkVsYVZqTklNRVJuYWpORmFYQnpaRkZzTUhKUGJEQlFOVWRLVmc9PSIsImVtYWlsIjoicm9iZXJ0by5waXZhQHp1Y2NoZXR0aS5pdCJ9fX0=
