# secret-postgres.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    environment: staging  
type: Opaque
stringData:
  POSTGRESQL_DATABASE: zmenu
  POSTGRESQL_USER: zmenu
  POSTGRESQL_PASSWORD: sviluppo  # cambia!
