# postgres-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    environment: staging
spec:
  replicas: 1
  selector: { matchLabels: { app: postgres } }
  template:
    metadata:
      labels: 
        app: postgres
        environment: staging
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: postgres
          image: registry.redhat.io/rhel8/postgresql-13:latest
          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: "200m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          envFrom:
            - secretRef: { name: postgres-secret }
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/pgsql/data
      volumes:
        - name: pgdata
          emptyDir: {}
