# manager-fe-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager-fe
  labels:
    environment: staging 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manager-fe
  template:
    metadata:
      labels: 
        environment: staging
        app: manager-fe
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: manager-fe
          image: ghcr.io/z-roberto-piva/zmenu_next_manager_frontend:0.0.3-1
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: API_PROXY_TARGET
              value: http://manager-be:8080
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx_manager.conf   # monta solo il file
            - name: tmp
              mountPath: /tmp
          # Se vuoi health checks:
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: nginx-conf
          configMap:
            name: manager-fe-nginx-conf
        - name: tmp
          emptyDir: {}

