# frontend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    environment: staging 
spec:
  selector: { app: frontend }
  ports:
    - name: http
      port: 80
      targetPort: 80
