# frontend-route.yaml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: frontend
  labels:
    environment: staging
    type: external
spec:
  to:  
    kind: Service
    name: frontend
  port: 
    targetPort: http
  tls:
    termination: edge
