kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: frontend-ext
  namespace: paas-zmenu-next
  labels:
    environment: staging
    type: external
spec:
  host: next-app.zhospitality.online
  to:
    kind: Service
    name: frontend
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    certificate: |-
      -----BEGIN CERTIFICATE-----
      MIIGazCCBVOgAwIBAgIQCC1D7JKeIEcFADrwInTTPjANBgkqhkiG9w0BAQsFADBg
      MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
      d3cuZGlnaWNlcnQuY29tMR8wHQYDVQQDExZHZW9UcnVzdCBUTFMgUlNBIENBIEcx
      MB4XDTI1MDYwNDAwMDAwMFoXDTI2MDYyNDIzNTk1OVowYDELMAkGA1UEBhMCSVQx
      DTALBgNVBAcTBExPREkxIjAgBgNVBAoTGVp1Y2NoZXR0aSBIb3NwaXRhbGl0eSBz
      cmwxHjAcBgNVBAMMFSouemhvc3BpdGFsaXR5Lm9ubGluZTCCASIwDQYJKoZIhvcN
      AQEBBQADggEPADCCAQoCggEBALf1F9sOPumg7+8UDIwiX3MfEAyPv7yz4wXKO1tG
      QhfCFunz8SFZaseizkxBM8NHE0BOK2Apju92u1qe2HgDyE0rrXbXkPwvmFpAn5tt
      HSbgMmTjs1Bz5CdduwMo/ckKV2vb7Edtaf2ALsemz7Lz+XHgYibkuLAEB+oJ/XKs
      G9BLJtnHZTvzSNSKxqcse5wfkxRPyUO5FXLy5h0leKF0tEV7GDfvl9u/Rj5TyEKf
      n0SbAIeIoAyx9179SxBiy0yUFkd98FpU7RyKDElDk0yLZ0XQv5YJlYqRgJFRHx3S
      amcuBU+H17zKHXGtK9ofSZL5w/4bM8zC94os6An0Xw1Jh2kCAwEAAaOCAx8wggMb
      MB8GA1UdIwQYMBaAFJRP1F2L5KTipoD+/dj5AO+jvgJXMB0GA1UdDgQWBBQCAHqJ
      LxI+BcIt4YXMNVc5A3PFnzAgBgNVHREEGTAXghUqLnpob3NwaXRhbGl0eS5vbmxp
      bmUwPgYDVR0gBDcwNTAzBgZngQwBAgIwKTAnBggrBgEFBQcCARYbaHR0cDovL3d3
      dy5kaWdpY2VydC5jb20vQ1BTMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggr
      BgEFBQcDAQYIKwYBBQUHAwIwPwYDVR0fBDgwNjA0oDKgMIYuaHR0cDovL2NkcC5n
      ZW90cnVzdC5jb20vR2VvVHJ1c3RUTFNSU0FDQUcxLmNybDB2BggrBgEFBQcBAQRq
      MGgwJgYIKwYBBQUHMAGGGmh0dHA6Ly9zdGF0dXMuZ2VvdHJ1c3QuY29tMD4GCCsG
      AQUFBzAChjJodHRwOi8vY2FjZXJ0cy5nZW90cnVzdC5jb20vR2VvVHJ1c3RUTFNS
      U0FDQUcxLmNydDAMBgNVHRMBAf8EAjAAMIIBfwYKKwYBBAHWeQIEAgSCAW8EggFr
      AWkAdwAOV5S8866pPjMbLJkHs/eQ35vCPXEyJd0hqSWsYcVOIQAAAZc56lB6AAAE
      AwBIMEYCIQC8RrA55+TpLD/Hb2dwNVrp6OoVF/CTb93mO1aq9zdZlAIhAL5ekaTK
      7tvD5Penufqkbp+ezpVShKMVmD6Lte+3+UEOAHYAZBHEbKQS7KeJHKICLgC8q08o
      B9QeNSer6v7VA8l9zfAAAAGXOepQLwAABAMARzBFAiBcxGPxsvRxapUTO/4Audnv
      dC5ddf5GSZEGyhOY78jUfwIhAKv3PRknIIsDD1NZsmIXivefu98ueAAS1elF8xgc
      ERXaAHYASZybad4dfOz8Nt7Nh2SmuFuvCoeAGdFVUvvp6ynd+MMAAAGXOepQRQAA
      BAMARzBFAiBzRHZk6lrj+BMPt+tKKElvmj8yEWogpqMMJKKbRBEyLAIhAIGnqFez
      +VbT+nx43OkMI5qkzEVTqRRBVcYtx3Nw1bN6MA0GCSqGSIb3DQEBCwUAA4IBAQBA
      OoCbVXdMxEGrqzLmiWmxQDMXC+2BHRYjwRbVuAZd5ETd6glKnvm9rHPDJbbi2E60
      DLx1xmsfoa8jllZhkGg5sh70OG1Ac1UNpPiB85/2u3Azsom8lhErqA2w+fGUtiHD
      +ImagGTnWITE0IDHvTTlebS87JaDOinwqsOdijoDMD5n5DGXYi4XvloUnFHGAuDx
      17CyKRXQi5mv5wzURmQ8bPkSPNlWlnKFY5fHuj8s2Ou8mJdOzcf7nF+C/8TGYnJu
      ZsbvU57VSyRkNo247Lb5tFge6DPOt5U5FlKtrf4JIbzfuB8aXdO43m6jOBUX1PAS
      SrQBGAIRlUxF96HSsA7v
      -----END CERTIFICATE-----
    key: |-
      -----BEGIN PRIVATE KEY-----
      MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC39RfbDj7poO/v
      FAyMIl9zHxAMj7+8s+MFyjtbRkIXwhbp8/EhWWrHos5MQTPDRxNATitgKY7vdrta
      nth4A8hNK61215D8L5haQJ+bbR0m4DJk47NQc+QnXbsDKP3JCldr2+xHbWn9gC7H
      ps+y8/lx4GIm5LiwBAfqCf1yrBvQSybZx2U780jUisanLHucH5MUT8lDuRVy8uYd
      JXihdLRFexg375fbv0Y+U8hCn59EmwCHiKAMsfde/UsQYstMlBZHffBaVO0cigxJ
      Q5NMi2dF0L+WCZWKkYCRUR8d0mpnLgVPh9e8yh1xrSvaH0mS+cP+GzPMwveKLOgJ
      9F8NSYdpAgMBAAECggEBAKv/+U8zkbVmahDzgQvh87czGxFzssYguCsovLkKBzAp
      pL0Y/qO89G83FYcNC/YRVbmxnTLriJ70OBdyIFqOxtEI/sb4pbJ2WhBBDjsIGdLI
      m7XjhTy7L19zbzF0OV6pUbYiyli6v/hrytGYcekT328PaxaMkvbYvgGhV53JuLPW
      ipm6hV1/VI3QFeuuOC4C62RbndBQeGoUkboax7uZUKCzTSE4aal7uM/j7LT2zdV0
      L812FVmSlDzfAXlq6bu4PHNwrJbhtYoiecMwk1zCsRDS+HTWR/LyNwzOKGHPiUHY
      g0InAMcI41PQ+aKTHecvf/hPN7U0gspvYW+zHv8/PrUCgYEA4c25W9JBl9F78esb
      obAwrRXw7DdjIVfdur0v6kKDMcl8zVDHyHRhz9Sj6qtSFjy5gEzUeuneynqjdiXm
      /h3O0Ou/iTKe1wES+WIQLgzrLRUXxpnyle3lQMEKxqOU1/ji6VKFXMK0AcbPo9QY
      w7IIlwIvLKMrx+34veh+smNMDmMCgYEA0I7I0+iJOs9tN0FcTD6qLlwF7UMnrpGr
      Dz9WU3eZq+tRcWx+l0SM3+YCcuiQ+1IHCXLw3HDAteML4s8zhpnkdQYPz3rFpY8x
      Y699MoRHVGY9R+DPavVWKIwvWKhDUO0hf53UwmZJjScwlDZAEtsId02Ils73RSNq
      euP06Lv+xsMCgYAsKQC0PXWIjHaSBGn+ACg04ZKhj996OOXrTG6fgOyJgx8+RCse
      P+yVKb/4+BJwuOWKevwfIbfpn3xycc0wK4I0B7cIzPaVk+czEIObjfk8cuCYfakc
      u07XkClcWceVSV6PRQ1B6+4qXshjAOrq8tmNNuck8rBwRFEeSubkWlkYgwKBgQCj
      sm8PZUXRU152MGcxsT4ChVhhkoRjERMjNKOdgBKuTlXuoSn7sWKhmvfxGXoyyX+c
      ewty+01Hdp6tt9TJoaEf+VIPmF3qRSqPA/9Q12LlbBpNgLdNTKQDz4SaIfg0XOwe
      LtQAgijZEhmfO7WvFxzeB41eUbTkH5hEPQjOZEDl4QKBgFfdhmFWQLfohkHE5xkt
      DPYFpjNDP+CYqv76EJHE7z3+17zCIdVYc/T6TRuZD3k7ic4+jgcDVliOqJGKcFIk
      cg3tooKkcyk/JX2yMbJhu4lW+SJwixsMfJ8vyI/fjye25Qfu3gFBgEQRZAnSK53I
      oUu3ki1R4oY3ltUPG1kNJhbn
      -----END PRIVATE KEY-----
    caCertificate: |-
      -----BEGIN CERTIFICATE-----
      MIIEjTCCA3WgAwIBAgIQDQd4KhM/xvmlcpbhMf/ReTANBgkqhkiG9w0BAQsFADBh
      MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
      d3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBH
      MjAeFw0xNzExMDIxMjIzMzdaFw0yNzExMDIxMjIzMzdaMGAxCzAJBgNVBAYTAlVT
      MRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5j
      b20xHzAdBgNVBAMTFkdlb1RydXN0IFRMUyBSU0EgQ0EgRzEwggEiMA0GCSqGSIb3
      DQEBAQUAA4IBDwAwggEKAoIBAQC+F+jsvikKy/65LWEx/TMkCDIuWegh1Ngwvm4Q
      yISgP7oU5d79eoySG3vOhC3w/3jEMuipoH1fBtp7m0tTpsYbAhch4XA7rfuD6whU
      gajeErLVxoiWMPkC/DnUvbgi74BJmdBiuGHQSd7LwsuXpTEGG9fYXcbTVN5SATYq
      DfbexbYxTMwVJWoVb6lrBEgM3gBBqiiAiy800xu1Nq07JdCIQkBsNpFtZbIZhsDS
      fzlGWP4wEmBQ3O67c+ZXkFr2DcrXBEtHam80Gp2SNhou2U5U7UesDL/xgLK6/0d7
      6TnEVMSUVJkZ8VeZr+IUIlvoLrtjLbqugb0T3OYXW+CQU0kBAgMBAAGjggFAMIIB
      PDAdBgNVHQ4EFgQUlE/UXYvkpOKmgP792PkA76O+AlcwHwYDVR0jBBgwFoAUTiJU
      IBiV5uNu5g/6+rkS7QYXjzkwDgYDVR0PAQH/BAQDAgGGMB0GA1UdJQQWMBQGCCsG
      AQUFBwMBBggrBgEFBQcDAjASBgNVHRMBAf8ECDAGAQH/AgEAMDQGCCsGAQUFBwEB
      BCgwJjAkBggrBgEFBQcwAYYYaHR0cDovL29jc3AuZGlnaWNlcnQuY29tMEIGA1Ud
      HwQ7MDkwN6A1oDOGMWh0dHA6Ly9jcmwzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydEds
      b2JhbFJvb3RHMi5jcmwwPQYDVR0gBDYwNDAyBgRVHSAAMCowKAYIKwYBBQUHAgEW
      HGh0dHBzOi8vd3d3LmRpZ2ljZXJ0LmNvbS9DUFMwDQYJKoZIhvcNAQELBQADggEB
      AIIcBDqC6cWpyGUSXAjjAcYwsK4iiGF7KweG97i1RJz1kwZhRoo6orU1JtBYnjzB
      c4+/sXmnHJk3mlPyL1xuIAt9sMeC7+vreRIF5wFBC0MCN5sbHwhNN1JzKbifNeP5
      ozpZdQFmkCo+neBiKR6HqIA+LMTMCMMuv2khGGuPHmtDze4GmEGZtYLyF8EQpa5Y
      jPuV6k2Cr/N3XxFpT3hRpt/3usU/Zb9wfKPtWpoznZ4/44c1p9rzFcZYrWkj3A+7
      TNBJE0GmP2fhXhP1D/XVfIW/h0yCJGEiV9Glm/uGOa3DXHlmbAcxSyCRraG+ZBkA
      7h4SeM6Y8l/7MBRpPCz6l8Y=
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIDjjCCAnagAwIBAgIQAzrx5qcRqaC7KGSxHQn65TANBgkqhkiG9w0BAQsFADBh
      MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
      d3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBH
      MjAeFw0xMzA4MDExMjAwMDBaFw0zODAxMTUxMjAwMDBaMGExCzAJBgNVBAYTAlVT
      MRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5j
      b20xIDAeBgNVBAMTF0RpZ2lDZXJ0IEdsb2JhbCBSb290IEcyMIIBIjANBgkqhkiG
      9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuzfNNNx7a8myaJCtSnX/RrohCgiN9RlUyfuI
      2/Ou8jqJkTx65qsGGmvPrC3oXgkkRLpimn7Wo6h+4FR1IAWsULecYxpsMNzaHxmx
      1x7e/dfgy5SDN67sH0NO3Xss0r0upS/kqbitOtSZpLYl6ZtrAGCSYP9PIUkY92eQ
      q2EGnI/yuum06ZIya7XzV+hdG82MHauVBJVJ8zUtluNJbd134/tJS7SsVQepj5Wz
      tCO7TG1F8PapspUwtP1MVYwnSlcUfIKdzXOS0xZKBgyMUNGPHgm+F6HmIcr9g+UQ
      vIOlCsRnKPZzFBQ9RnbDhxSJITRNrw9FDKZJobq7nMWxM4MphQIDAQABo0IwQDAP
      BgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIBhjAdBgNVHQ4EFgQUTiJUIBiV
      5uNu5g/6+rkS7QYXjzkwDQYJKoZIhvcNAQELBQADggEBAGBnKJRvDkhj6zHd6mcY
      1Yl9PMWLSn/pvtsrF9+wX3N3KjITOYFnQoQj8kVnNeyIv/iPsGEMNKSuIEyExtv4
      NeF22d+mQrvHRAiGfzZ0JFrabA0UWTW98kndth/Jsw1HKj2ZL7tcu7XUIOGZX1NG
      Fdtom/DzMNU+MeKNhJ7jitralj41E6Vf8PlwUHBHQRFXGU7Aj64GxJUTFy8bJZ91
      8rGOmaFvE7FBcf6IKshPECBV1/MUReXgRPTqh5Uykw7+U0b6LJ3/iyK5S9kJRaTe
      pLiaWN0bfVKfjllDiIGknibVb63dDcY3fe0Dkhvld1927jyNxF1WW6LZZm6zNTfl
      MrY=
      -----END CERTIFICATE-----
  wildcardPolicy: None
